name: "Build"
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Launch and test
        run: |
          cd dataplatform-core
          chmod +x *.sh
          chmod +x scripts/*.sh
          chmod +x kafka2mongo/gradlew
          for i in $(seq 2)
          do
            echo "Run $i"
            scripts/config.sh
            ./launch.sh -t
            ./stop.sh
          done
  release:
    needs:
      - build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Release
        run: |
          npm install
          npx semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
      - name: Log in to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Retrieve version
        run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for fiware2kafka
        uses: docker/metadata-action@75359341f62c2d990e0aa8543e545c74eec643ff
        with:
          images: ${{ secrets.DOCKER_IMAGENAME1 }}
          tags: |
            ${{steps.tag.outputs.version}}
            latest

      - name: Build and push fiware2kafka image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: .
          file: fiware2kafka/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Extract metadata (tags, labels) for kafka2mongo
        uses: docker/metadata-action@75359341f62c2d990e0aa8543e545c74eec643ff
        with:
          images: ${{ secrets.DOCKER_IMAGENAME2 }}
          tags: |
            ${{steps.tag.outputs.version}}
            latest

      - name: Build and push kafka2mongo image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: .
          file: kafka2mongo/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}